version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - vulnerable_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - vulnerable_network
    depends_on:
      - server

  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    networks:
      - vulnerable_network
    depends_on:
      - server

networks:
  vulnerable_network:
    driver: bridge
